export HOMEDIR=/home/ko/Desktop/git/DataTrsfer/DataTrsfer
SOURCE_DIR = $(HOMEDIR)/src

COMPILE_DIRS = $(SOURCE_DIR)

all:
	cd $(SOURCE_DIR); make
clean:
	cd $(SOURCE_DIR); rm *.o;
	cd $(HOMEDIR)/bin; rm *;
